insert into public.scenarios (slug, category, title, sender, content, link_hint, locale, is_verified, is_published)
values
  ('traffic-fine', 'message', 'Phạt Nguội Giao Thông', 'CẢNH SÁT GIAO THÔNG', 'CẢNH BÁO: Phương tiện mang biển số của bạn đã vi phạm giao thông. Truy cập phatnguoivn.com.vn để nộp phạt trong 24 giờ hoặc bị khóa giấy phép lái xe.', 'phatnguoivn.com.vn', 'vi-VN', true, true),
  ('bank-account-lock', 'message', 'Khóa Tài Khoản Ngân Hàng', 'VIETCOMBANK THÔNG BÁO', 'Tài khoản của quý khách vừa bị đăng nhập bất thường từ thiết bị lạ. Xác minh ngay tại vietcombank-security.com để tránh bị khóa tài khoản vĩnh viễn.', 'vietcombank-security.com', 'vi-VN', true, true),
  ('zalo-prize', 'message', 'Trúng Thưởng Zalo / Tri Ân', 'ZALO OFFICIAL', 'Chúc mừng! Tài khoản Zalo của bạn đã trúng thưởng iPhone 15 Pro và tiền mặt 50 triệu đồng từ chương trình Tri ân 10 năm. Nhận thưởng tại: zalo-trung-thuong.net', 'zalo-trung-thuong.net', 'vi-VN', true, true),
  ('held-parcel', 'message', 'Bưu Kiện Hỏa Tốc Bị Giữ', 'VIETTEL POST', 'Bưu kiện mã VTP-2806-XXXX của quý khách bị giữ tại hải quan do nghi chứa vật phẩm vi phạm. Vui lòng xác minh tại viettelpost-xacminh.com trong 12 giờ.', 'viettelpost-xacminh.com', 'vi-VN', true, true),
  ('impersonated-child', 'message', 'Mượn Tiền Giả Danh Con Cháu', 'Nguyễn Minh Khoa (Con)', 'Mẹ ơi, con đang cần gấp 8 triệu để đóng học phí hôm nay không thì bị đuổi học. Mẹ chuyển vào số tài khoản 1234-5678-9012 ngân hàng Techcombank giúp con với ạ. Con xin lỗi mẹ vì làm phiền.', null, 'vi-VN', true, true),
  ('deepfake-police-call', 'call', 'Deepfake Video Call Công An', 'CÔNG AN THÀNH PHỐ', 'Đây là Thiếu tá Nguyễn Văn Hùng - Công an TP.HCM. Tên của bà có liên quan đến đường dây rửa tiền quốc tế. Để tránh bị bắt giữ, bà cần chuyển 30 triệu đồng vào tài khoản tạm giữ trong 2 giờ.', null, 'vi-VN', true, true),
  ('emergency-hospital-call', 'call', 'Cuộc Gọi Cấp Cứu Khẩn Cấp', 'BỆNH VIỆN BẠCH MAI', 'Tôi là bác sĩ trực cấp cứu Bệnh viện Bạch Mai. Con trai bà vừa nhập viện do tai nạn giao thông nghiêm trọng. Chúng tôi cần bà chuyển gấp 15 triệu đồng viện phí trước khi phẫu thuật.', null, 'vi-VN', true, true),
  ('fake-order-job', 'investment', 'Tuyển Cộng Tác Viên Chốt Đơn', 'Tuyển Dụng Shopee VN', 'Chào chị! Em cần tìm cộng tác viên chốt đơn hàng Shopee tại nhà, làm 2-3 tiếng/ngày, lương 500k-2 triệu/ngày. Không cần kinh nghiệm, không cần đặt cọc. Chị có muốn tham gia không ạ? Đăng ký ngay tại: ctv-shopee-vn.com', 'ctv-shopee-vn.com', 'vi-VN', true, true),
  ('high-return-investment', 'investment', 'Đầu Tư Tài Chính Lợi Nhuận Cao', 'Hội Đầu Tư Chứng Khoán VN', 'Chào bác! Hội đầu tư chứng khoán của chúng tôi đang có chương trình đặc biệt: lãi suất 10-15%/ngày, an toàn tuyệt đối. Bác chỉ cần đầu tư 5 triệu, sau 7 ngày nhận về 8-10 triệu. Tham gia tại: dautuvn-pro.com', 'dautuvn-pro.com', 'vi-VN', true, true),
  ('social-benefit-scam', 'investment', 'Trợ Cấp Xã Hội / Quỹ Từ Thiện', 'HỘI CHỮ THẬP ĐỎ VN', 'Kính gửi công dân! Theo danh sách hộ gia đình khó khăn, gia đình bạn được hỗ trợ 2.000.000 đồng từ Quỹ An sinh Xã hội 2026. Vui lòng xác nhận nhận tiền tại: hotrocovid-vn.com trước 17h hôm nay.', 'hotrocovid-vn.com', 'vi-VN', true, true)
on conflict (slug) do update set
  category = excluded.category,
   title = excluded.title,
   sender = excluded.sender,
   content = excluded.content,
   link_hint = excluded.link_hint,
   locale = excluded.locale,
   is_verified = excluded.is_verified,
   is_published = excluded.is_published,
   updated_at = now();

-- Demo-only community clusters. These are synthetic seed records, not real submissions.
insert into public.scam_clusters (
  fingerprint,
  category,
  locale,
  title,
  summary,
  title_en,
  summary_en,
  report_count,
  contributor_count,
  reviewer_count,
  upvote_count,
  is_verified,
  is_trending,
  updated_at
)
values
  (
    'seed-fake-delivery-payment',
    'message',
    'vi-VN',
    'Giả danh giao hàng, yêu cầu thanh toán gấp',
    'Tin nhắn giả mạo đơn vị vận chuyển tạo áp lực chuyển khoản hoặc bấm liên kết để nhận bưu kiện.',
    'Fake delivery payment requests',
    'Messages impersonate delivery services and pressure people to pay or open a parcel link.',
    18,
    11,
    3,
    14,
    true,
    true,
    now()
  ),
  (
    'seed-impersonated-family-transfer',
    'message',
    'vi-VN',
    'Giả danh người thân để mượn tiền',
    'Kẻ gian dùng tài khoản giống người thân và tạo tình huống khẩn cấp để yêu cầu chuyển tiền ngay.',
    'Family impersonation and urgent transfers',
    'Scammers impersonate relatives and create an emergency to pressure an immediate transfer.',
    15,
    9,
    3,
    12,
    true,
    true,
    now()
  ),
  (
    'seed-fake-account-verification',
    'message',
    'vi-VN',
    'Xác minh tài khoản và lấy mã OTP',
    'Thông báo tài khoản gặp vấn đề và yêu cầu cung cấp OTP hoặc thông tin đăng nhập qua trang giả.',
    'Fake account verification and OTP theft',
    'Alerts claim an account problem and request OTPs or login details through a fake page.',
    12,
    8,
    2,
    9,
    true,
    false,
    now()
  ),
  (
    'seed-investment-group-profit',
    'investment',
    'vi-VN',
    'Nhóm đầu tư hứa lợi nhuận bất thường',
    'Nhóm chat hứa lãi cao và dùng ảnh chụp lợi nhuận để thúc giục nạp tiền vào nền tảng không rõ nguồn gốc.',
    'Investment groups promising unusual returns',
    'Chat groups promise high returns and use profit screenshots to push deposits into unknown platforms.',
    10,
    7,
    2,
    8,
    true,
    false,
    now()
  )
on conflict (fingerprint) do update set
  category = excluded.category,
  locale = excluded.locale,
  title = excluded.title,
  summary = excluded.summary,
  title_en = excluded.title_en,
  summary_en = excluded.summary_en,
  report_count = excluded.report_count,
  contributor_count = excluded.contributor_count,
  reviewer_count = excluded.reviewer_count,
  upvote_count = excluded.upvote_count,
  is_verified = excluded.is_verified,
  is_trending = excluded.is_trending,
  updated_at = now();
